import type { BaseMessage } from '@langchain/core/messages'
import type { AI } from './ai'
import type { Search } from './search'
import type { MemoryVectorStore } from './store'

export type AppConfig = {
  ai: AI
  botName: string
  search: Search
  square: SquareStatus
}

export type BotStatus = {
  [key: string]: SquareStatus
}

export type MemberStatus = {
  name: string
  messages: Message[]
}

export type Message = {
  id: string
  content: BaseMessage
}

export type SquareStatus = {
  botId: string
  conversation: BaseMessage[]
  members: { [key: string]: MemberStatus }
  vectorStore: MemoryVectorStore
}

/** Represents a memory vector used for storing content and its corresponding embedding. */
export interface MemoryVector {
  /**
   * The content associated with the vector.
   *
   * This can be any string data, such as text, or labels.
   */
  content: string

  /**
   * The numerical embedding corresponding to the content.
   *
   * The embedding is represented as an array of numbers, typically generated by embedding models.
   */
  embedding: number[]

  /** The unique identifier for the vector. */
  id?: string
}
